/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/flower.glb')
  const { actions } = useAnimations(animations, group)
  const position = [-6, 0.5, 11]
  const rotation = [0, Math.PI, 0]
  useEffect(() => {
    actions.Bloom.play()
  })
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      position={position}
      rotation={rotation}
      scale={0.1}
      receiveShadow
      castShadow
    >
      <group name='Scene'>
        <group name='Node_0' scale={0.1}>
          <group name='FlowerChin' position={[7.74, 339.77, -22.77]}>
            <mesh
              name='Cylinder_4'
              geometry={nodes.Cylinder_4.geometry}
              material={materials.Stem}
              position={[2.72, -36.04, 20.15]}
              rotation={[-1.99, -0.69, -2.37]}
            />
            <mesh
              name='Cylinder_5'
              geometry={nodes.Cylinder_5.geometry}
              material={materials.Stem}
              position={[-10.98, -23.22, 31.78]}
              rotation={[0.8, -0.78, 0.34]}
            />
            <mesh
              name='Cylinder_6'
              geometry={nodes.Cylinder_6.geometry}
              material={materials.Stem}
              position={[-37.83, -4.59, -2.3]}
              rotation={[Math.PI / 2, -0.96, 1.88]}
            />
            <mesh
              name='Cylinder_7'
              geometry={nodes.Cylinder_7.geometry}
              material={materials.Stem}
              position={[21.94, -29.21, 3.4]}
              rotation={[-0.84, -0.57, -0.72]}
            />
            <mesh
              name='Cylinder_8'
              geometry={nodes.Cylinder_8.geometry}
              material={materials.Stem}
              position={[4.36, -34.78, -23.76]}
              rotation={[-1, -0.31, 0.08]}
            />
          </group>
          <group name='Petal' position={[11.99, 412.22, -37.64]}>
            <mesh
              name='Cube'
              geometry={nodes.Cube.geometry}
              material={materials.Petal}
              position={[67.9, -24.33, 1.73]}
              rotation={[-Math.PI / 2, -0.42, Math.PI / 2]}
            />
            <mesh
              name='Cube_2'
              geometry={nodes.Cube_2.geometry}
              material={materials.Petal}
              position={[-11.63, -21.6, 91.62]}
              rotation={[-1.82, 0.03, -0.2]}
            />
            <mesh
              name='Cube_3'
              geometry={nodes.Cube_3.geometry}
              material={materials.Petal}
              position={[-67.59, -31.38, 1.76]}
              rotation={[-Math.PI / 2, 0.4, -Math.PI / 2]}
            />
            <mesh
              name='Cube_4'
              geometry={nodes.Cube_4.geometry}
              material={materials.Petal}
              position={[-2.6, -24.56, -90.83]}
              rotation={[-1.34, -0.01, 2.93]}
            />
          </group>
          <group name='Stamen' position={[11.63, 443.64, -22.8]}>
            <mesh
              name='Cube_5'
              geometry={nodes.Cube_5.geometry}
              material={materials.Stamen}
              position={[1.08, 0, 39.82]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name='Cube_6'
              geometry={nodes.Cube_6.geometry}
              material={materials.Stamen}
              position={[1.08, 0, 3.22]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name='Cube_7'
              geometry={nodes.Cube_7.geometry}
              material={materials.Stamen}
              position={[1.08, 0, -33.2]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name='Sphere'
              geometry={nodes.Sphere.geometry}
              material={materials.Stamen}
              position={[0, 49.84, 36.51]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name='Sphere_2'
              geometry={nodes.Sphere_2.geometry}
              material={materials.Stamen}
              position={[0, 49.84, -0.09]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name='Sphere_3'
              geometry={nodes.Sphere_3.geometry}
              material={materials.Stamen}
              position={[0, 49.84, -36.51]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name='Stem' position={[3, 182.26, -1.46]}>
            <mesh
              name='Cylinder_2'
              geometry={nodes.Cylinder_2.geometry}
              material={materials.Stem}
              position={[3.73, -118.6, 27.47]}
              rotation={[0.65, -Math.PI / 2, 0]}
            />
            <mesh
              name='Cylinder_3'
              geometry={nodes.Cylinder_3.geometry}
              material={materials.Stem}
              position={[5.86, -97.7, -50.68]}
              rotation={[1.07, 1.27, -2.07]}
            />
            <mesh
              name='Cylinder'
              geometry={nodes.Cylinder.geometry}
              material={materials.Stem}
              position={[0, -132.26, 0.46]}
              rotation={[0, -Math.PI / 2, 0]}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/flower.glb')
