/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF, useCursor } from "@react-three/drei";
import useStore from "../../helpers/store";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/plus.glb");
  const [addMessage, setAddMessage] = useStore((state) => [
    state.addMessage,
    state.setAddMessage,
  ]);
  const [hovered, hover] = useState(false);
  useCursor(hovered);
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={0.1}
      position={[-8, 6.5, -19]}
      rotation={[0, Math.PI / 2, 0]}
      onClick={() => setAddMessage(true)}
      onPointerOver={(e) => (e.stopPropagation(), hover(true))}
      onPointerOut={() => hover(false)}
    >
      <group position={[0.09, 3.45, -0.17]} scale={0.25}>
        <mesh
          geometry={nodes.Cube.geometry}
          material={materials["Material.001"]}
          scale={0.1}
        />
        <mesh
          geometry={nodes.Cube_2.geometry}
          material={materials["Material.001"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/plus.glb");
