/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Plywood({ position, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/plywood.gltf')
  return (
    <group ref={group} position={position} {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials.wood}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[5, 5, 5]}
      />
    </group>
  )
}

useGLTF.preload('/plywood.gltf')
