/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from "react";
import * as THREE from "three";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model({ ...props }) {
  const environment = useRef();
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/wishbearSplineRun.glb");
  const { actions } = useAnimations(animations, group);
  const [mixer] = useState(() => new THREE.AnimationMixer());
  const position = [0.5, 0, 1];
  const speed = 0.25;

  useEffect(() => void mixer.clipAction(animations[0], group.current).play());
  useFrame((state, delta) => {
    const t = state.clock.getElapsedTime();

    environment.current.rotation.y -=
      Math.sin(delta * 0.5) * Math.cos((delta * 0.5) / 2) * 1.5;

    mixer.update(delta * 0.9);
  });
  return (
    <group ref={environment} position={[-6, 0.5, 11]}>
      <group
        ref={group}
        {...props}
        dispose={null}
        scale={0.025}
        position={position}
        rotation={[0, -Math.PI / 2, 0]}
      >
        <group name="Scene">
          <group name="Node_0" position={[0, 2.33, 0]} scale={0.1}>
            <group
              name="Arms"
              position={[1.75, 216.48, 86.5]}
              rotation={[-2.07, 0, 0]}
            >
              <mesh
                name="Cube_9"
                geometry={nodes.Cube_9.geometry}
                material={materials.Skin}
                position={[37.83, 133.79, -21.37]}
                rotation={[1.43, -0.44, -1.57]}
              />
              <mesh
                name="Cube_8"
                geometry={nodes.Cube_8.geometry}
                material={materials.Skin}
                position={[-37.72, 131.59, -17.61]}
                rotation={[-1.27, 0.44, -Math.PI / 2]}
              />
            </group>
            <group
              name="Body"
              position={[0, 101.45, -15.14]}
              scale={[0.84, 0.91, 1]}
            >
              <mesh
                name="Tail"
                geometry={nodes.Tail.geometry}
                material={materials.Skin}
                position={[-1.95, -23.88, -69.36]}
                rotation={[-2.4, 0, -Math.PI / 2]}
                scale={0.1}
              />
              <mesh
                name="Toros"
                geometry={nodes.Toros.geometry}
                material={materials.Skin}
                position={[0, 8.58, 4.54]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={[0.91, 1.05, 1]}
              />
            </group>
            <group
              name="Directional_Light"
              position={[-0.88, 378.24, 288.73]}
              rotation={[0.53, -0.2, -0.33]}
            >
              <directionalLight
                name="Directional_Light_Orientation"
                intensity={0.5}
                decay={2}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <group position={[0, 0, -1]} />
              </directionalLight>
            </group>
            <group
              name="Head"
              position={[0, 199.98, 0]}
              rotation={[0.17, 0, 0]}
              scale={[1, 1, 0.96]}
            >
              <mesh
                name="Cube"
                geometry={nodes.Cube.geometry}
                material={materials.Skin}
                position={[0.63, -21.16, -10.76]}
              />
              <mesh
                name="Cube_2"
                geometry={nodes.Cube_2.geometry}
                material={materials.Skin}
                position={[30.33, 12.78, -29.78]}
                rotation={[-1.84, 0.28, -1.6]}
                scale={[0.78, 1.03, 0.99]}
              />
              <mesh
                name="Cube_3"
                geometry={nodes.Cube_3.geometry}
                material={materials.Skin}
                position={[-32.01, 11.32, -29.37]}
                rotation={[-1.84, -0.2, -1.57]}
                scale={[0.78, 1.03, 0.99]}
              />
              <mesh
                name="Cube_4"
                geometry={nodes.Cube_4.geometry}
                material={materials.Eye}
                position={[11.04, 11.3, 22.05]}
                rotation={[-2.44, 0.03, -1.55]}
                scale={[0.43, 0.57, 0.44]}
              />
              <mesh
                name="Cube_5"
                geometry={nodes.Cube_5.geometry}
                material={materials.Eye}
                position={[-7.66, 11.3, 22.05]}
                rotation={[-2.44, 0.03, -1.55]}
                scale={[0.43, 0.57, 0.44]}
              />
              <mesh
                name="Cube_6"
                geometry={nodes.Cube_6.geometry}
                material={materials.Eye}
                position={[1.73, 8.62, 54.6]}
                rotation={[-0.9, 0, -Math.PI / 2]}
                scale={[0.98, 1, 1]}
              />
            </group>
            <group
              name="Legs"
              position={[1.95, 31.23, -6.45]}
              scale={[1.08, 0.99, 1.17]}
            >
              <mesh
                name="Cube_11"
                geometry={nodes.Cube_11.geometry}
                material={materials.Skin}
                position={[26.23, 37.88, -6.36]}
                rotation={[-2.69, 0, -Math.PI / 2]}
              />
              <mesh
                name="Cube_10"
                geometry={nodes.Cube_10.geometry}
                material={materials.Skin}
                position={[-25.92, 38.26, -6.36]}
                rotation={[-0.54, 0, -Math.PI / 2]}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/wishbearSplineRun.glb");
