/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Wood({ position, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/wood.gltf");
  return (
    <group ref={group} position={position} {...props} dispose={null}>
      <group scale={0.06}>
        <mesh
          geometry={nodes.group_0.geometry}
          material={materials["wood.002"]}
          position={[149.21, 0, 0]}
          rotation={[0, 1.57, 0]}
        />
        <mesh
          geometry={nodes.group_0001.geometry}
          material={materials["wood.003"]}
          position={[149.21, 0, 0]}
          rotation={[0, 1.57, 0]}
        />
        <mesh
          geometry={nodes.group_0002.geometry}
          material={materials.wood}
          position={[149.21, 0, 0]}
          rotation={[0, 1.57, 0]}
        />
        <mesh
          geometry={nodes.group_0003.geometry}
          material={materials.wood}
          position={[149.21, 0, 0]}
          rotation={[0, 1.57, 0]}
        />
        <mesh
          geometry={nodes.group_0004.geometry}
          material={materials.wood}
          position={[149.21, 0, 0]}
          rotation={[0, 1.57, 0]}
        />
        <mesh
          geometry={nodes.group_0005.geometry}
          material={materials.wood}
          position={[149.21, 0, 0]}
          rotation={[0, 1.57, 0]}
        />
        <mesh
          geometry={nodes.group_0006.geometry}
          material={materials.wood}
          position={[149.21, 0, 0]}
          rotation={[0, 1.57, 0]}
        />
        <mesh
          geometry={nodes.group_0007.geometry}
          material={materials.wood}
          position={[149.21, 0, 0]}
          rotation={[0, 1.57, 0]}
        />
        <mesh
          geometry={nodes.group_0009.geometry}
          material={materials.material}
          position={[149.21, 0, 0]}
          rotation={[0, 1.57, 0]}
        />
        <mesh
          geometry={nodes.group_0010.geometry}
          material={materials.wood}
          position={[149.21, 0, 0]}
          rotation={[0, 1.57, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/wood.gltf");
